### ISSUE TITLE
FileNotFoundException  - preprocessor_output.txt

### ISSUE THREAD

**Issue by tomas-knap** [rkadlecek/ml-experiments#4]
I tried to run java -cp target/ml-experiments.jar sk.kadlecek.mle.SingleDataset resources/experiment1/phones_dataset.arff

But I got: 
```
Exception in thread "main" java.io.FileNotFoundException: preprocessor_output.txt (No such file or directory)

at java.io.FileInputStream.open0(Native Method)

at java.io.FileInputStream.open(FileInputStream.java:195)

at java.io.FileInputStream.<init>(FileInputStream.java:138)

at java.io.FileInputStream.<init>(FileInputStream.java:93)

at java.io.FileReader.<init>(FileReader.java:58)

at sk.kadlecek.mle.ml.Common.readDataFile(Common.java:88)

at sk.kadlecek.mle.SingleDataset.main(SingleDataset.java:29)
```

**Comment by tomas-knap** [comment]
Separate datasets works: java -cp target/ml-experiments.jar sk.kadlecek.mle.SeparateDatasets resources/experiment2/phones_dataset.arff resources/experiment2/tablets_dataset.arff

**Comment by rkadlecek** [comment]
Thank you for reporting the issue, it is now fixed in **master** branch.
